### ISSUE TITLE
simplest way to generate opensextant JSON output

### ISSUE THREAD

**Issue by johnrfrank** [OpenSextant/OpenSextantToolbox#10]
I would like to generate a set of *example* JSON output from OpenSextant.  What is the simplest way to do this?  Is there a running instance somewhere that I could send a few sample documents?

Things I tried:

 * downloading OpenSextant-v1.4 from the downloads site:  docs out of date, but got this to almost work:
      java -Xmx1500m  -Dsolr.solr.home=../opensextant/Gazetteer/solr/  -Dopensextant.home="."   -cp "./lib/*" org.mitre.opensextant.apps.OpenSextantRunner -g gate/OpenSextant_GeneralPurpose.gapp  -f JSON -i /data/west-africa-clean_visible -o /data/west-africa-clean_visible-opensextant -t /data/tmp

That fails when it turns out that my solr+jetty system does not have data loaded into it.  The various build.xml files for ant in the `opensextant` git repo don't "just work."

 * in the opensextant git repo:  ./OpenSextantToolbox/script/geocode.sh doc.txt doc JSON  also tries to run an ant compile that does not "just work"

 * using opensextant-toolbox-2.0 release zip from the download site, if we run

          opensextant-toolbox-2.0/lib$ ln -s solr Solr

then the examples.xml is more valid (looks like that directory capitalization naming error might have resulted from someone developing on MacOS's default case-insensitive file system)... but it fails like this:

$ ant -f examples.xml 
Buildfile: /ebs/third/opensextant/opensextant-toolbox-2.0/examples.xml

run.examples:
     [echo] 
     [echo] -----------------------------------------------
     [echo] Running the Geotagger Example
     [echo] -----------------------------------------------
     [java] Initializing
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
     [java]     at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:460)
     [java]     at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:546)
     [java]     at org.opensextant.examples.GeotaggerExample.main(GeotaggerExample.java:75)
     [java] Java Result: 1
     [echo] 
     [echo] -------------------------------------------------------------------------------
     [echo] Running the General Purpose Entity Extractor Example
     [echo] -------------------------------------------------------------------------------
     [java] Initializing
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
     [java]     at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:460)
     [java]     at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:546)
     [java]     at org.opensextant.examples.GeneralPurposeTaggerExample.main(GeneralPurposeTaggerExample.java:73)
     [java] Java Result: 1
     [echo] 
     [echo] --------------------------------------------------
     [echo] Running the Solr Matcher Example
     [echo] --------------------------------------------------
     [java] No arg supplied for location of solr gazetteer. Using environment variable
     [java] Exception reading text from filematcherTest.txt

Thanks for any pointers.

jrf

**Comment by dlutz2** [comment]
No further activity
