### ISSUE TITLE
extendedPlaceName always null

### ISSUE THREAD

**Issue by haleystorm** [OpenSextant/OpenSextantToolbox#16]
I am running the opensextant-toolbox 2.2 built from the latest source with the most recent gazetteer data (USGS_date=20160601, NGA_date=20160718) and whenever I do a post to the lookup service like

```
curl -X GET http://localhost:8182/opensextant/lookup/json/Kabul
```

the results show extendedPlaceName is null. 

```
[{
    "placeName": "Kabul",
    "expandedPlaceName": null,
    "nameType": "name",
    "nameTypeSystem": null,
    "countryCode": "RU",
    "admin1": "RS54",
    "admin2": null,
    "featureClass": "Geo.featureType.Area",
    "featureCode": "AREA",
    "sourceNameID": null,
    "sourceFeatureID": null,
    "placeID": "NGA10907567",
    "source": "NGA",
    "nameBias": 0.0,
    "idBias": 0.03999999910593033,
    "acountry": false,
    "anAdmin1": false,
    "nationalCapital": false,
    "latitude": 54.8074,
    "longitude": 72.8947,
    "geocoord": {
        "latitude": 54.8074,
        "longitude": 72.8947
    },
    "abbreviation": false
}, 
...
```
This is true for csv as well. Is there a better example to run that would show what should be in that field?

**Comment by dlutz2** [comment]
The expandedPlaceName is to show a place name when the placeName is an abbreviation.
 Try
curl -X GET http://localhost:8182/opensextant/lookup/json/DC

**Comment by haleystorm** [comment]
Perfect. Thanks!
